apiVersion: v1
kind: Service
metadata:
  name: crc-simple-api-lb
  namespace: student0
spec:
  type: NodePort
  selector:
    app: crc-simple-api
  ports:
    - port: 8002
      targetPort: 9000
      nodePort: 30081