apiVersion: v1
kind: Service
metadata:
  name: svc-warzywniak
spec:
  type: NodePort
  selector:
    app: warzywniak-stateful
  ports:
  - name: insert-port
    port: 80
    targetPort: 8000
    nodePort: 30085
  - name: list-port
    port: 81
    targetPort: 8001
    nodePort: 30086
