apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: warzywniak-statefulset
spec:
  serviceName: "svc-warzywniak"
  replicas: 1
  selector:
    matchLabels:
      app: warzywniak-stateful
  template:
    metadata:
      labels:
        app: warzywniak-stateful
    spec:
      containers:
      - name: insert-container
        image: gadzina13/warzywniak-insert:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: fruits-storage
          mountPath: "/data"
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
          requests:
            cpu: "20m"
            memory: "64Mi"

      - name: list-container
        image: gadzina13/warzywniak-list:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
        volumeMounts:
        - name: fruits-storage
          mountPath: "/data"
          readOnly: true
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
          requests:
            cpu: "20m"
            memory: "64Mi"

  volumeClaimTemplates:
  - metadata:
      name: fruits-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
