apiVersion: v1
kind: PersistentVolume
metadata:
  name: fruits-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/warzywniak-data"
