apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ENV_NAME: "{{ .Values.config.ENV_NAME }}"
  LOCATION: "{{ .Values.config.LOCATION }}"
  VERSION: "{{ .Values.config.VERSION }}"
