apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: ENV_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: ENV_NAME
        - name: LOCATION
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: LOCATION
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: VERSION
        - name: DB_HOST
          value: {{ .Release.Name }}-postgres
        - name: DB_NAME
          value: {{ .Values.postgres.db }}
        - name: DB_USER
          value: {{ .Values.postgres.user }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: DB_PASSWORD
        resources:
          limits:
            cpu: {{ .Values.frontend.resources.limits.cpu }}
            memory: {{ .Values.frontend.resources.limits.memory }}
          requests:
            cpu: {{ .Values.frontend.resources.requests.cpu }}
            memory: {{ .Values.frontend.resources.requests.memory }}
