apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: full-sites-ingress
  namespace: student0
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - crc1.com
    - www.crc1.com
    - crc2.com
    - crc3.com
    - crc4.com
    secretName: crc-tls
  rules:
  - host: crc1.com
    http:
      paths:
      - backend:
          service:
            name: nginx-two-sites-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: www.crc1.com
    http:
      paths:
      - backend:
          service:
            name: nginx-two-sites-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: crc2.com
    http:
      paths:
      - backend:
          service:
            name: nginx-two-sites-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: crc3.com
    http:
      paths:
      - backend:
          service:
            name: nginx-two-sites-service
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: crc4.com
    http:
      paths:
      - backend:
          service:
            name: nginx-two-sites-service
            port:
              number: 80
        path: /
        pathType: Prefix