apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-two-sites-config
data:
  default.conf: |
    server {
      listen 80;
      server_name crc1.com;

      root /usr/share/nginx/html/crc1;
      index index.html;

      location / {
          try_files $uri $uri.html $uri/ =404;
      }

      error_page 404 /404.html;
      location = /404.html {
          internal;
      }
    }

    server {
      listen 80;
      server_name crc2.com;

      root /usr/share/nginx/html/crc2;
      index index.html;

      location / {
          try_files $uri $uri/ =404;
      }
    }