apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-two-sites-config
data:
  default.conf: |
    server {
      listen 80;
      server_name crc1.com www.crc1.com;

      root /usr/share/nginx/html/crc1;
      index index.html;

      location / {
          try_files $uri $uri.html $uri/ =404;
      }

      error_page 404 /404.html;
      location = /404.html {
          internal;
      }
    }

    server {
      listen 80;
      server_name crc2.com;

      root /usr/share/nginx/html/crc2;
      index index.html;

      location / {
          try_files $uri $uri/ =404;
      }
    }
    
    # crc3.com redirect
    server {
      listen 80;
      server_name crc3.com;
      return 301 https://crc2.com$request_uri;
    }
    
    # crc4.com - Flask przez reverse proxy
    server {
      listen 80;
      server_name crc4.com;

      location / {
          proxy_pass http://crc4-flask-service.student0.svc.cluster.local:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }