apiVersion: v1
kind: Service
metadata:
  name: nginx-two-sites-service
spec:
  selector:
    app: nginx-two-sites
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crc4-flask-service
  namespace: student0
spec:
  selector:
    app: crc4-flask
  ports:
  - port: 80
    targetPort: 5000