apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-logger
spec:
  selector:
    matchLabels:
      app: node-logger
  template:
    metadata:
      labels:
        app: node-logger
    spec:
      containers:
      - name: logger
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "🕒 $(date): Hello from node $(hostname)";
              sleep 30;
            done
        resources:
          limits:
            cpu: "50m"
            memory: "64Mi"
          requests:
            cpu: "10m"
            memory: "32Mi"
